# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nosyntax.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nosyntax.proto',
  package='',
  serialized_pb='\n\x0enosyntax.proto\"\x1c\n\tMyRequest\x12\x0f\n\x07myfield\x18\x01 \x02(\x05\"\x1e\n\nMyResponse\x12\x10\n\x08myresult\x18\x01 \x02(\x05\x32/\n\tMyService\x12\"\n\x07\x44oStuff\x12\n.MyRequest\x1a\x0b.MyResponse')




_MYREQUEST = _descriptor.Descriptor(
  name='MyRequest',
  full_name='MyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='myfield', full_name='MyRequest.myfield', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=18,
  serialized_end=46,
)


_MYRESPONSE = _descriptor.Descriptor(
  name='MyResponse',
  full_name='MyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='myresult', full_name='MyResponse.myresult', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=48,
  serialized_end=78,
)

DESCRIPTOR.message_types_by_name['MyRequest'] = _MYREQUEST
DESCRIPTOR.message_types_by_name['MyResponse'] = _MYRESPONSE

class MyRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MYREQUEST

  # @@protoc_insertion_point(class_scope:MyRequest)

class MyResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MYRESPONSE

  # @@protoc_insertion_point(class_scope:MyResponse)


# @@protoc_insertion_point(module_scope)
