# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto2.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto2.proto',
  package='',
  serialized_pb='\n\x0cproto2.proto\"\x1d\n\nMyRequest2\x12\x0f\n\x07myfield\x18\x01 \x02(\x05\"\x1f\n\x0bMyResponse2\x12\x10\n\x08myresult\x18\x01 \x02(\x05\x32\x32\n\nMyService2\x12$\n\x07\x44oStuff\x12\x0b.MyRequest2\x1a\x0c.MyResponse2')




_MYREQUEST2 = _descriptor.Descriptor(
  name='MyRequest2',
  full_name='MyRequest2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='myfield', full_name='MyRequest2.myfield', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=16,
  serialized_end=45,
)


_MYRESPONSE2 = _descriptor.Descriptor(
  name='MyResponse2',
  full_name='MyResponse2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='myresult', full_name='MyResponse2.myresult', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=47,
  serialized_end=78,
)

DESCRIPTOR.message_types_by_name['MyRequest2'] = _MYREQUEST2
DESCRIPTOR.message_types_by_name['MyResponse2'] = _MYRESPONSE2

class MyRequest2(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MYREQUEST2

  # @@protoc_insertion_point(class_scope:MyRequest2)

class MyResponse2(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MYRESPONSE2

  # @@protoc_insertion_point(class_scope:MyResponse2)


# @@protoc_insertion_point(module_scope)
