# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto3.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto3.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0cproto3.proto\"\x1d\n\nMyRequest3\x12\x0f\n\x07myfield\x18\x01 \x01(\x05\"\x1f\n\x0bMyResponse3\x12\x10\n\x08myresult\x18\x01 \x01(\x05\x32\x32\n\nMyService3\x12$\n\x07\x44oStuff\x12\x0b.MyRequest3\x1a\x0c.MyResponse3b\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MYREQUEST3 = _descriptor.Descriptor(
  name='MyRequest3',
  full_name='MyRequest3',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='myfield', full_name='MyRequest3.myfield', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=45,
)


_MYRESPONSE3 = _descriptor.Descriptor(
  name='MyResponse3',
  full_name='MyResponse3',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='myresult', full_name='MyResponse3.myresult', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=78,
)

DESCRIPTOR.message_types_by_name['MyRequest3'] = _MYREQUEST3
DESCRIPTOR.message_types_by_name['MyResponse3'] = _MYRESPONSE3

MyRequest3 = _reflection.GeneratedProtocolMessageType('MyRequest3', (_message.Message,), dict(
  DESCRIPTOR = _MYREQUEST3,
  __module__ = 'proto3_pb2'
  # @@protoc_insertion_point(class_scope:MyRequest3)
  ))
_sym_db.RegisterMessage(MyRequest3)

MyResponse3 = _reflection.GeneratedProtocolMessageType('MyResponse3', (_message.Message,), dict(
  DESCRIPTOR = _MYRESPONSE3,
  __module__ = 'proto3_pb2'
  # @@protoc_insertion_point(class_scope:MyResponse3)
  ))
_sym_db.RegisterMessage(MyResponse3)


# @@protoc_insertion_point(module_scope)
